#include "pc/ui/ui_manual.h"

const char* gManualText =
"# F-Zero X PC Port Manual\n\n"
"## Introduction\n"
"Welcome to the F-Zero X PC Port (Decompilation). This project aims to bring the classic N64 racer to modern platforms with native performance, enhanced visuals, and new features from F-Zero GX/AX.\n\n"
"## Features Overview\n"
"This port includes features that are either implemented or planned for future updates. Please refer to the Roadmap for development status.\n\n"
"### Graphics\n"
"- **Resolution:** Supports arbitrary resolutions including 4K and Ultrawide (21:9).\n"
"- **Widescreen:** Native widescreen support without stretching HUD elements.\n"
"- **High FPS:** Unlocked framerate (up to 360Hz) with interpolation for smooth gameplay.\n"
"- **Textures:** Support for high-resolution texture packs and model replacements.\n"
"- **Lighting:** Enhanced lighting engine with dynamic shadows and bloom (Planned).\n\n"
"### Audio\n"
"- **High Quality:** Replaced MIDI sequences with high-quality streaming audio (WAV/FLAC).\n"
"- **3D Spatial Audio:** Implements HRTF for realistic sound positioning (Planned).\n"
"- **Volume Control:** Independent sliders for Music, SFX, and Voice.\n\n"
"### Input\n"
"- **Controller Support:** Native support for XInput, DirectInput, and SDL2-compatible controllers.\n"
"- **Mapping:** Fully remappable controls for all actions.\n"
"- **Deadzone:** Adjustable analog stick deadzone and sensitivity.\n"
"- **Rumble:** Force feedback support for compatible controllers.\n\n"
"### Gameplay\n"
"- **Physics Modes:**\n"
"  - *Classic (X):* Original N64 physics. 100% accurate.\n"
"  - *Modern (GX):* Physics from F-Zero GX including Momentum Turbo Slide (MTS).\n"
"  - *Arcade (AX):* Physics from F-Zero AX arcade cabinets.\n"
"- **Story Mode:** A new mission-based campaign inspired by GX's story mode (Planned).\n"
"- **Track Editor:** Built-in track editor to create and share custom courses (Planned).\n\n"
"### Cheats & Mods\n"
"- **God Mode:** Infinite energy and invincibility.\n"
"- **Unlock All:** Instantly unlocks all machines, cups, and difficulties.\n"
"- **Debug Menu:** Access to internal game variables and state machine visualization.\n\n"
"## Troubleshooting\n"
"- **Performance:** If experiencing stuttering, try lowering the resolution or disabling V-Sync.\n"
"- **Input:** If your controller is not recognized, check the SDL2 mapping database.\n"
"- **Crashes:** Please report crashes on the GitHub repository with a reproduction log.\n\n"
"## Credits\n"
"- **Decompilation Team:** The original authors of the N64 decompilation.\n"
"- **PC Port Team:** Contributors to the PC platform layer.\n"
"- **Community:** Special thanks to the F-Zero speedrunning community.\n";
