#include "pc/ui/ui_manual.h"

const char* gManualText =
"# F-Zero X PC Port Manual\n\n"
"## Introduction\n"
"Welcome to the ultimate F-Zero X experience. This port combines the precision of the N64 original with the high-octane mechanics of F-Zero GX, the arcade intensity of F-Zero AX, and the modern flair of spiritual successors like Redout.\n\n"
"## Features Overview\n"
"### Graphics & Immersion (Redout-Inspired)\n"
"- **Post-Processing:**\n"
"  - *Motion Blur:* Simulates high-speed camera shutter effects.\n"
"  - *Chromatic Aberration:* Adds color fringing at extreme speeds.\n"
"  - *Lens Flare:* Anamorphic flares from engines and sunlight.\n"
"  - *Bloom:* Dynamic glow for neon tracks and energy strips.\n"
"- **Camera:**\n"
"  - *Dynamic FOV:* Field of view increases with speed for a greater sense of velocity.\n"
"  - *Cockpit View:* Fully immersive first-person perspective.\n"
"  - *Camera Shake:* Procedural vibration based on boost usage and collisions.\n"
"- **HUD Styles:** Choose between Classic X, Modern GX, or Minimalist Redout interfaces.\n\n"
"### Gameplay Mechanics (GX/AX/Redout)\n"
"- **Physics Engines:**\n"
"  - *Classic (X):* 100% accurate N64 physics.\n"
"  - *Modern (GX):* Includes Momentum Turbo Slide (MTS) and heavy gravity.\n"
"  - *Arcade (AX):* Tuned for arcade cabinet steering wheels.\n"
"  - *Redout Mode:* Adds lateral strafing and shield mechanics.\n"
"- **Advanced Techniques:**\n"
"  - *Quick Turn (X):* Sharp turning via L+R triggers.\n"
"  - *Side Attack (X/GX):* Aggressive lateral ramming.\n"
"  - *Spin Attack (GX/AX):* Rotational attack to damage nearby enemies.\n"
"  - *Shift Boost (Snaking):* Gain speed by shifting weight during drifts.\n"
"- **Health System:** Option for Redout-style shield regeneration vs classic energy strips.\n\n"
"### Customization & Garage\n"
"- **Pilot Profile:** Track stats for Body, Boost, and Grip.\n"
"- **Paint Shop:** Customize Primary, Secondary, and Tertiary colors (GX Style).\n"
"- **Emblem Editor:** Create custom pixel art emblems and decals.\n"
"- **Parts Shop:** Purchase new boosters, cockpits, and bodies with race winnings.\n\n"
"### Online Multiplayer\n"
"- **30-Player Death Race:** Massive online races with rollback netcode.\n"
"- **Lobby Browser:** Find open servers worldwide.\n"
"- **Spectator Mode:** Watch live races as a free-roaming camera drone.\n"
"- **Netcode Settings:** Adjust rollback frames and input delay to minimize lag.\n\n"
"### Track Editor (Expansion)\n"
"- **Construction Kit:** Build custom tracks using pieces from X, GX, and AX.\n"
"- **Segments:** Straights, Curves, Loops, Pipes, Cylinders, Corkscrews.\n"
"- **Surfaces:** Asphalt, Dirt, Ice, Heal Strips, Slip Zones.\n"
"- **Sharing:** Save and load custom tracks to share with the community.\n\n"
"## Troubleshooting\n"
"- **Performance:** Lower 'Motion Blur' or 'Bloom' if framerate drops.\n"
"- **Input:** Ensure your controller is mapped in the 'Input' tab.\n"
"- **Network:** Port forward UDP 7000 for hosting direct connections.\n\n"
"## Credits\n"
"- **Decompilation Team:** The original authors of the N64 decompilation.\n"
"- **PC Port Team:** Contributors to the PC platform layer.\n"
"- **Community:** Special thanks to the F-Zero speedrunning community.\n";
